# Service listener configuration
http:
  port: "8081"

# The project artifact and version data 
project:
  artifact: "${project.artifactId}"
  version: "${project.version}"
  
# API Specification and autodiscovery
api:  
  group: "${restconnector.api.spec.group}"
  artifact: "${restconnector.api.spec.artifact}"
  version: "${restconnector.api.spec.version}"
  spec: "resource::${api.group}:${api.artifact}:${api.version}:raml:zip:api.raml"
  id: "17910674"

# Service messages
messages:
  order-previously-created: "The order was previously created"
  order-success: "The order was integrated successfully"
  internal-error: "An internal error was produced"
  backend-error: "There was a problem while trying to access the backend repository"

  
customer:
  host: "customer-service-url"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"
  
order:
  host: "order-service-url"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"

item:
  host: "item-service-url"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"
  
# Logging - Provide next values as system properties
# logzio.token: "MyToken"
# logzio.url: "MyLogzioURL"