# Environment where the service is running
env: local

# Service listener configuration
http:
  port: "8081"

# The project artifact and version data 
project:
  artifact: "${project.artifactId}"
  version: "${project.version}"
  
# API Specification and autodiscovery
api:  
  group: "${restconnector.api.spec.group}"
  artifact: "${restconnector.api.spec.artifact}"
  version: "${restconnector.api.spec.version}"
  spec: "resource::${api.group}:${api.artifact}:${api.version}:raml:zip:api.raml"
  id: "0"

# Open Telemetry configuration
otel:
  servicename: "${project.name}-local"

# Service messages
messages:
  order-previously-created: "The order was previously created"
  order-success: "The order was integrated successfully"
  order-create-error: "The order could not be created"
    
customer:
  host: "micorp-customer-sapi-dev.us-w1.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"
  
order:
  host: "micorp-order-sapi-dev.us-w1.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"

item:
  host: "micorp-item-sapi-dev.us-w1.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/api"

# Components to configure:
# - OpenTelemtry connector
# - Logzio (logging platform)
# - Mulesoft Gatekeeper